import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df=pd.read_csv("week2_mini_project/netflix.csv")
df["cast"]=df["cast"].fillna("Unknown")
df["country"]=df["country"].fillna("Unknown")
df=df.dropna(subset=["date_added"])
df["rating"]=df["rating"].fillna(df["rating"].mode()[0])
df=df.dropna(subset=["duration"])
df["director"]=df["director"].fillna("Unknown")
#Does Netflix have more Movies or TV Shows
plt.figure(figsize=(8,5))
ax=sns.countplot(x="type",data=df,color="Red")
for container in ax.containers:
    ax.bar_label(container)
plt.title("Netflix Content Type Distribution")
plt.xlabel("Content type")
plt.ylabel("Number of Titles")
plt.show()
print(df["type"].value_counts())
print("Netflix has significantly more Movies than TV Shows. Movies make up the majority of the Netflix content library.")
# in India has the most Content

country_count=df["country"].value_counts()
print(country_count.head(10))
print("Some records have unknown country information, so the country analysis may not represent the complete Netflix catalog.")
#which Rating is Most Common?
rating_count=df["rating"].value_counts()
print(rating_count.head(10))
plt.figure(figsize=(8,5))
sns.countplot(y="rating",data=df,order=df["rating"].value_counts().index)
plt.xlabel("Number of Titles")
plt.ylabel("Rating")
plt.show()
print("The majority of Netflix content is rated TV-MA, showing that Netflix has a large amount of content targeted toward adult audiences.")
#Which years had the highest number of Netflix releases?
year_count=df["release_year"].value_counts().sort_index()
print(year_count.tail(10))
plt.figure(figsize=(8,5))
sns.lineplot(x=year_count.index,y=year_count.values,color="yellow",marker="o",linestyle="--")
plt.title("Netflix Content Releases over years")
plt.xlabel("Release year")
plt.ylabel("Number of Titles")
plt.show()
print("Netflix content grew rapidly during the 21st century, with the highest number of titles released around 2018. The years between 2000 and 2020 contributed the majority of content in the dataset, while very few titles were released before 2000.")
#What are the most common genres on Netflix?
genre_count=df["listed_in"].value_counts()
print(genre_count.head(10))
plt.figure(figsize=(8,5))
sns.countplot(y="listed_in",data=df,order=df["listed_in"].value_counts().head(10).index,color="Green")
plt.title("Top 10 netflix Genres")
plt.xlabel("Number of Titles")
plt.ylabel("Genre")
plt.show()
print("Insights of Netflix Dataset:")
print(" Movies are more common than TV Shows (6128 vs 2666)")
print("United States has the most content (2809)")
print("🇮🇳 India is the second largest contributor (972)")
print("TV-MA is the most common rating")
print(" Most content was released after 2000, with a peak around 2018")
print(" Dramas and International Movies are among the most common genres")
