import pandas as pd
df=pd.read_csv("Day9/Students.csv")
print(df)
print("First two rows:")
print(df.head(2))
print("Last two rows:")
print(df.tail(2))
print(df.info())
print("describing the students data")
print(df.describe())
print(df["Marks"])
print(df.loc[3])
print("student who got more than 90 marks:")
print(df[df["Marks"]>90])
