import pandas as pd
df=pd.read_csv("day14/Tested.csv")
print(df.head(5))
print(df.shape)
df.info()
print(df.columns)
print(df.isnull())
print("missing vallues:")
print(df.isnull().sum())
print(df.describe())
numerical_cols=df.select_dtypes(include=['number']).columns.tolist()
categorical_cols=df.select_dtypes(exclude=['number']).columns.tolist()
print(numerical_cols)
print(categorical_cols)