import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
tips=sns.load_dataset("tips")
print(tips.head(5))
print(tips.columns)
print(tips.shape)
tips.info()
print("Missing Values:")
print(tips.isnull().sum())
print("Duplicate Rows:")
print(tips.duplicated().sum())
print("Describe the tips")
print(tips.describe())
sns.histplot(tips["total_bill"])
plt.show()
sns.boxplot(x=tips["total_bill"])
plt.show()
sns.countplot(x=tips["day"])
plt.show()
sns.scatterplot(x=tips["total_bill"],y=tips["tip"])
plt.show()
correlation= tips.corr(numeric_only=True)
sns.heatmap(correlation,annot=True)
plt.show()
