num1=int(input("enter first number:"))
num2=int(input("enter second number:"))
add= num1+num2
sub=num1-num2
multiply= num1*num2
division=num1 / num2
print("add=",add)
print("subtraction=",sub)
print("multiplication=",multiply)
print("division=",division)