import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("A matrix of 3X3:")
print(A)
print("shape:",A.shape)
B=np.array([[4,5,6],[1,7,8],[2,3,6]])
print("Addition of two matrices:")
print(A+B)
print("Scalar matrix multiplication:")
print(5*A)
print("Identity Matrix:")
print(np.identity(3))
Zero_matrix=np.zeros((2,3))
print("Zero matrix of size 2 X3")
print(Zero_matrix)
Random_matrix=np.random.rand(3,3)
print("Random matrix: ",Random_matrix)
rows=Random_matrix.shape[0]
cols=Random_matrix.shape[1]
print("num of rows:")
print(rows)
print("num of columns")
print(cols)
print("Transpose matrix:")
print(A.T)
